//LOGIN
export const LOGIN_DEFAULT = 'LOGIN_DEFAULT';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_USERNAME_CHANGED = 'LOGIN_USERNAME_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';
export const LOGOUT = 'LOGOUT';
